[package]
name = "pocket-cli"
version = "0.1.0"
authors = ["ozbe <1372945+ozbe@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pocket = { git = "https://github.com/ozbe/rust-pocket.git", branch = "serde" }
structopt = "0.3"